#!/bin/bash -eu

set -o pipefail

readonly FFMPEG_VERSION=${1:?}
readonly ARCH=${2:-win32}
readonly BUILD_DIR=${3:-$HOME/.cache/ci/r128gain/ffmpeg-${ARCH}}
readonly OUTPUT_FILE=${4:-ffmpeg.exe}
readonly PROC_COUNT=$(grep -c '^processor' /proc/cpuinfo)


configure() {
  if [ $ARCH = "win32" ]
  then
    arch_params="--arch=x86 --target-os=mingw32 --cross-prefix=i686-w64-mingw32-"
  elif [ $ARCH = "win64" ]
  then
    arch_params="--arch=x86 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32-"
  else
    echo 'Invalid arch' >&2
    exit 1
  fi
  ./configure $arch_params \
              --enable-gpl \
              --enable-version3 \
              --enable-static \
              --disable-shared \
              $(./configure --help | grep -oF -- '--disable-autodetect' || true) \
              --disable-programs \
              --enable-ffmpeg \
              --disable-doc \
              --disable-encoders \
              --enable-encoder=pcm_s16le \
              --disable-decoders \
              $(ffmpeg -hide_banner -codecs | grep '^ D.A' | cut -d ' ' -f 3 | xargs -I'{}' echo --enable-decoder={}) \
              --disable-hwaccels \
              --disable-muxers \
              --enable-muxer=null \
              --disable-parsers \
              --disable-bsfs \
              --disable-protocols \
              --enable-protocol=file \
              --disable-devices \
              --disable-filters \
              --enable-filter=afifo \
              --enable-filter=aformat \
              --enable-filter=anullsink \
              --enable-filter=aresample \
              --enable-filter=asplit \
              --enable-filter=concat \
              --enable-filter=ebur128 \
              --enable-filter=replaygain \
              --disable-debug
}

repo_dir=$BUILD_DIR/$FFMPEG_VERSION
if [ "$FFMPEG_VERSION" = "master" ]
then
  branch_name=master
else
  branch_name=release/$FFMPEG_VERSION
fi

if [ -d $repo_dir ]
then
  # repo dir already exists
  cd $repo_dir
  git fetch

  if [ "$(git rev-parse @)" != "$(git rev-parse origin/$branch_name)" ]
  then
    # update
    git pull

    # cleanup
    make clean || true
    make distclean || true

    # (re)configure
    configure
  fi
else
  # clone & set branch
  git clone https://git.ffmpeg.org/ffmpeg.git $repo_dir
  cd $repo_dir
  git checkout $branch_name

  # configure
  configure
fi

# build
make -j $PROC_COUNT

cp "$repo_dir/ffmpeg.exe" "$OUTPUT_FILE"
